travis:
  secure:
    BINSTAR_TOKEN: Susmyw+Z7nreohlKP8RBfhlvH4MeFJPg+/izKJ2JKPTAJkphwPtNL13cOtSHz/lYjR2ykRw+MZiAcXUaT5enrAKGStVjIEcAnJX+E4mYLb0bl8H7vSsIwdAVW5MFvPtmRo5qq9Sxj1Oz0Y3fuM9+wvt/7c7pz7/ElZgj5VDWWM1I7ZFDzWbDw947ORPtj1+Z55nJ1tCtNzdsp1SsIpr1WPCB7oS/bsD8eDaFwGKWq60QwPDNm3xEh6Q0YEOlR8jEK1QRJoAPCjXqZjzYfh34YBOd8MDkMvEvk0XLIKjUKrtgqMfYTkd63cP5WxvyqZc5JlJavmzRCosAg31rNZ9BDaQ8iZa/i+GyPHiXqzqPNHwvqoM11al+OrlfvvnD4ycsMGmMz9yp+EjL7K32b+m28f6+6AJcrlEJfXybRFY7cGPJtezhmqTQFeY8dqnJR1b2Ag41j8fFuk6Hquv2rdYLn97ZoL2yxfMUuet6XkWEvc9YuMSkr5We/FyIetNNqYjYE4ofI+t1+o6EiUA8XriMlESnZ5x7xR6i2J7fQOxi43G+bXrN4kDJaZG78QXPQOJMuzrEQ4q7F55Z4/Q/yvnlKhUBRLcTvhiC01csHD3gWvPySjqypwKVmC+2vvJiDF8yRs1GUToiKhwdgGlFWTwS+uvHVvbX20fJWRpzxA64s4A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
